services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # INSTALLER
    #
    Xxii\FormBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('XxiiFormBundle')"

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Xxii\FormBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

# add more services, or override services that need manual wiring
#    Xxii\FormBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
